/*
 * The Rust kernels as a table of operations: the key hashes and the hash
 * table, for node modules that call them through the bridge's kernel
 * registry instead of linking the library. _PG_init installs the table.
 */
#include "postgres.h"

#include "internal.h"

const TessKernelOps tess_kernel_ops = {
	TESS_ABI_INITIALIZER(TESS_KERNEL_OPS_ABI_VERSION, TessKernelOps),
	.table_format_version = TESS_TABLE_FORMAT_VERSION,
	.int4_hash = tess_int4_hash,
	.int4_hash_next = tess_int4_hash_next,
	.int8_hash = tess_int8_hash,
	.int8_hash_next = tess_int8_hash_next,
	.table_size = tess_table_size,
	.table_create = tess_table_create,
	.table_stats = tess_table_stats,
	.table_chunk_init = tess_table_chunk_init,
	.table_append = tess_table_append,
	.table_link = tess_table_link,
	.table_link_grouped = tess_table_link_grouped,
	.table_probe = tess_table_probe,
	.table_next_match = tess_table_next_match,
	.table_gather = tess_table_gather,
	.table_record = tess_table_record,
	.table_find_or_insert = tess_table_find_or_insert,
	.table_payload = tess_table_payload,
	.table_scan = tess_table_scan,
	.table_regrow = tess_table_regrow,
	.table_next_in_group = tess_table_next_in_group,
	.table_accumulate = tess_table_accumulate,
	.table_gather_key = tess_table_gather_key,
	.table_bloom_words = tess_table_bloom_words,
	.table_bloom = tess_table_bloom,
	.bloom_probe = tess_bloom_probe,
	.bloom_shared_words = tess_bloom_shared_words,
	.bloom_shared_init = tess_bloom_shared_init,
	.table_try_build_bloom = tess_table_try_build_bloom,
	.bloom_shared_ready = tess_bloom_shared_ready,
	.bloom_shared_probe = tess_bloom_shared_probe,
	.build_counters_init = tess_build_counters_init,
	.build_report = tess_build_report,
	.build_take_chunk = tess_build_take_chunk,
	.build_add_duplicates = tess_build_add_duplicates,
	.build_totals = tess_build_totals,
	.build_step = tess_build_step,
	.table_fingerprint = tess_table_fingerprint,
	.spill_header_write = tess_spill_header_write,
	.spill_header_read = tess_spill_header_read,
	.table_append_partitioned = tess_table_append_partitioned,
	.table_split = tess_table_split,
	.bloom_add = tess_bloom_add,
	.table_find_or_insert_partitioned = tess_table_find_or_insert_partitioned,
	.table_combine = tess_table_combine,
	.table_spill_words = tess_table_spill_words,
	.table_spill_init = tess_table_spill_init,
	.table_spill_split = tess_table_spill_split,
	.table_spill_partitions = tess_table_spill_partitions,
	.table_spill_add_bytes = tess_table_spill_add_bytes,
	.table_spill_evict = tess_table_spill_evict,
	.table_spill_flags = tess_table_spill_flags,
	.table_spill_records = tess_table_spill_records,
	.table_spill_start = tess_table_spill_start,
	.table_spill_take_file = tess_table_spill_take_file,
	.table_spill_take_alone = tess_table_spill_take_alone,
	.round_step = tess_round_step,
	.bloom_shared_add = tess_bloom_shared_add,
	.table_spill_evictions = tess_table_spill_evictions,
};
